name: docker-build-and-push
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  release:
    types: [published]
env:
  REGISTRY: docker-registry.server.cloud.felipegalvao.xyz
  IMAGE_NAME: galvaofelipe/faster-whisper-server
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: [Dockerfile.cuda, Dockerfile.cpu]
        include:
          - dockerfile: Dockerfile.cuda
            tag-suffix: -cuda
          - dockerfile: Dockerfile.cpu
            tag-suffix: -cpu
    steps:
      - uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            suffix=${{ matrix.tag-suffix}},onlatest=true
          tags: |
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Login to Private Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache-${{ matrix.type }}
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache-${{ matrix.type }},mode=max